# goal
uint8 num_cargo # 1 or 2 (0 is pointless, 3+ is impossible)
bool eject
---
# result
bool success
bool timed_out
---
# feedback
uint8 WAITING_FOR_SHOOTER=0
uint8 WAITING_FOR_INDEXER=1
uint8 WAITING_FOR_ROTATION=2
uint8 WAITING_FOR_SHOOTER_AND_ROTATION=3 # If shooter is not up to speed and not aligned correctly
uint8 state # which state the current cargo is in
uint8 cargo_shot # how many cargo have been launched 
