# Fourber = 
uint8 CUBE=0
uint8 VERTICAL_CONE=1
uint8 BASE_TOWARDS_US_CONE=2 
uint8 BASE_AWAY_US_CONE=3
uint8 piece

uint8 INTAKE=0
uint8 LOW_NODE=1
uint8 MIDDLE_NODE=2
uint8 HIGH_NODE=3
uint8 mode

uint8 SAFETY_INTAKE_LOW=1 # intaking
uint8 SAFETY_MID=2 # when colliding with elevator vertical support
uint8 SAFETY_HIGH=3 # above certain height
uint8 SAFETY_TO_NO_SAFETY=4 # basically we need a way for the elevater actionlib to tell the fourber server that is is ok to transition to NO_SAFTEY, and still let other nodes pass in NO_SAFTEY and not mess it up
uint8[] safety_positions # looks up config value on where to go based on this, ignored if safety is false
# if you are not the elevater, leave this list empty
---
#result
bool success # if we got there
string message # debugging for errors
---
#feedback
bool success # if we got there
