# goal
uint8 CUBE=0
uint8 VERTICAL_CONE=1
uint8 BASE_TOWARDS_US_CONE=2 
uint8 BASE_AWAY_US_CONE=3
uint8 piece

bool unflip_outtake
---
# result
bool timed_out
---
# feedback
uint8 PATHER=0
uint8 INTAKE=1
uint8 DONE=2
uint8 status