# goal
uint8 CUBE=0
uint8 VERTICAL_CONE=1
uint8 BASE_TOWARDS_US_CONE=2 
uint8 BASE_AWAY_US_CONE=3
uint8 DOUBLE_SUBSTATION=254 # *caution* moves all the way up, then down when preempted
uint8 piece

bool unflip_fourbar

uint8 INTAKE=0
uint8 OUTTAKE_CUBE=1
uint8 OUTTAKE_CONE=2
uint8 outtake
---
# result
bool success
---
# feedback
uint8 PATHER=0
uint8 INTAKE=1
uint8 DONE=2
uint8 status