# goal
uint8 HYBRID=0
uint8 MID=1
uint8 HIGH=2
uint8 node

bool align_intake # if this is true, move sideways: centered to the node -> game piece in intake centered to node (using terabees or something)

# if override_game_piece is true, will use `piece` instead of the detected game piece
bool override_game_piece

uint8 CUBE=0
uint8 VERTICAL_CONE=1
uint8 BASE_TOWARDS_US_CONE=2 
uint8 BASE_AWAY_US_CONE=3
uint8 piece

uint8 MOVE=0
uint8 PLACE_RETRACT=1
uint8 step

bool from_Trex # if we are in the safe position for placing
---
# result
bool success
---
# feedback
