# goal
uint8 HIGH_GOAL=0
uint8 EJECT=1 # currently uses a static speed
uint8 mode
float64 wheel_speed #main wheel speed
float64 hood_wheel_speed
bool hood_position #false for down, true for up
---
# result
---
# feedback
bool close_enough # whether the speed is within a margin of error of the desired speed
