#defining goal
float64 left_shooter_speed
float64 right_shooter_speed

---
#defining result
bool success

---
#feedback
bool is_shooting_at_speed
float64 left_percent_complete
float64 right_percent_complete
