#defining goal
float64 top_left_speed
float64 top_right_speed
float64 bottom_left_speed
float64 bottom_right_speed
bool leave_spinning

---
#defining result
bool success

---
#feedback
bool is_shooting_at_speed
float64 top_left_percent_complete
float64 top_right_percent_complete
float64 bottom_left_percent_complete
float64 bottom_right_percent_complete