# goal
uint8 SPEAKER=0
uint8 TRAP=1
uint8 AMP=2
uint8 PLOP_FRONT=3
uint8 SUBWOOFER=4
uint8 PODIUM=5
uint8 LOB_PASS=6
uint8 SHOT_PASS=7
uint8 SLIDE=8
uint8 START_AUTO=9
uint8 mode
float64 distance
bool setup_only # just spin up
bool leave_spinning
bool cancel_movement # will OVERRIDE other fields, cancels lower level servers and exits 
---
# result
bool success
---
# feedback
uint8 SPINNING=0
uint8 PIVOTING=1
uint8 SHOOTING=2
uint8 current_stage # if we have a bunch of different stages to manage
# currently unset:
float64 current_speed
float64 target_speed