Header header

bool lockingSwitchButton
bool lockingSwitchPress
bool lockingSwitchRelease

bool topRedButton
bool topRedPress
bool topRedRelease

bool leftRedButton
bool leftRedPress
bool leftRedRelease

bool rightRedButton
bool rightRedPress
bool rightRedRelease

bool leftSwitchUpButton
bool leftSwitchUpPress
bool leftSwitchUpRelease

bool leftSwitchDownButton
bool leftSwitchDownPress
bool leftSwitchDownRelease

bool rightSwitchUpButton
bool rightSwitchUpPress
bool rightSwitchUpRelease

bool rightSwitchDownButton
bool rightSwitchDownPress
bool rightSwitchDownRelease

bool leftBlueButton
bool leftBluePress
bool leftBlueRelease

bool rightBlueButton
bool rightBluePress
bool rightBlueRelease

bool yellowButton
bool yellowPress
bool yellowRelease

bool leftGreenButton
bool leftGreenPress
bool leftGreenRelease

bool rightGreenButton
bool rightGreenPress
bool rightGreenRelease

bool topGreenButton
bool topGreenPress
bool topGreenRelease

bool bottomGreenButton
bool bottomGreenPress
bool bottomGreenRelease

bool bottomSwitchUpButton
bool bottomSwitchUpPress
bool bottomSwitchUpRelease

bool bottomSwitchDownButton
bool bottomSwitchDownPress
bool bottomSwitchDownRelease
