Header header

float64 voltage
float64 totalCurrent

float64[24] current
string[24] thingsPluggedIn
bool[24] channelBreakerFault
bool[24] stickyChannelBreakerFault

bool    enabled
bool    switchableChannelState
bool    canWarning
bool    stickyCanWarning
bool    stickyCanBusOff
bool    hardwareFault
bool    stickyHasReset
int32   moduleNumber
uint32  firmwareMajor
uint32  firmwareMinor
uint32  firmwareFix
uint32  hardwareMajor
uint32  hardwareMinor
