Header header

#data returned by HAL function calls

int32 fpgaVersion
int64 fpgaRevision
uint64 fpgaTime
bool userButton
bool isSysActive
bool isBrownedOut
float64 inputVoltage
float64 inputCurrent
float64 voltage3V3
float64 current3V3
bool enabled3V3
int32 faultCount3V3
float64 voltage5V
float64 current5V
bool enabled5V
int32 faultCount5V
float64 voltage6V
float64 current6V
bool enabled6V
int32 faultCount6V
RobotControllerCANData canData

#status values returned by the same HAL function calls

string fpgaVersion_status
string fpgaRevision_status
string fpgaTime_status
string userButton_status
string isSysActive_status
string isBrownedOut_status
string inputVoltage_status
string inputCurrent_status
string voltage3V3_status
string current3V3_status
string enabled3V3_status
string faultCount3V3_status
string voltage5V_status
string current5V_status
string enabled5V_status
string faultCount5V_status
string voltage6V_status
string current6V_status
string enabled6V_status
string faultCount6V_status
string canData_status
