python3 ~/2023RobotCode/zebROS_ws/src/tf_object_detection/src/onnx_to_tensorrt.py arucotag_decoder.onnx --output arucotag_decoder.engine --fp16 --batch-size-min=1 --batch-size-max=4 --batch-size=4 --max-workspace-size=1073741824
#python3 ~/2023RobotCode/zebROS_ws/src/tf_object_detection/src/onnx_to_tensorrt.py arucotag_decoder.onnx --output arucotag_decoder_int8.engine --fp16 --int8 --batch-size-min=1 --batch-size-max=4 --batch-size=4 --max-workspace-size=1073741824 --dataset-path /home/ubuntu/tensorflow_workspace/2023Game/data/combined_88_test --calibration-file arucotag_decoder.calib

#python3 ~/2023RobotCode/zebROS_ws/src/tf_object_detection/src/onnx_to_tensorrt.py arucotag_roi_detector.onnx --output arucotag_roi_detector.engine --fp16 --input-width=1088 --input-width-min=512 --input-width-max=2048 --max-workspace-size=1073741824
python3 ~/2023RobotCode/zebROS_ws/src/tf_object_detection/src/onnx_to_tensorrt.py arucotag_roi_detector.onnx --output arucotag_roi_detector_int8.engine --fp16 --input-width=1088 --input-width-min=512 --input-width-max=2048 --int8 --max-workspace-size=1073741824 --dataset-path /home/ubuntu/tensorflow_workspace/2023Game/data/combined_88_test --calibration-file arucotag_roi_detector.calib
python3 ~/2023RobotCode/zebROS_ws/src/tf_object_detection/src/onnx_to_tensorrt.py arucotag_roi_detector.onnx --output arucotag_roi_detector_int8_batch4.engine --fp16 --input-width=1088 --batch-size=4 --int8 --max-workspace-size=1073741824 --dataset-path /home/ubuntu/tensorflow_workspace/2023Game/data/combined_88_test --calibration-file arucotag_roi_detector.calib
python3 ~/2023RobotCode/zebROS_ws/src/tf_object_detection/src/onnx_to_tensorrt.py arucotag_roi_detector.onnx --output arucotag_roi_detector_int8_batch5.engine --fp16 --input-width=1088 --batch-size=5 --int8 --max-workspace-size=1073741824 --dataset-path /home/ubuntu/tensorflow_workspace/2023Game/data/combined_88_test --calibration-file arucotag_roi_detector.calib
python3 ~/2023RobotCode/zebROS_ws/src/tf_object_detection/src/onnx_to_tensorrt.py arucotag_roi_detector.onnx --output arucotag_roi_detector_int8_batch9.engine --fp16 --input-width=1088 --batch-size=9 --int8 --max-workspace-size=1073741824 --dataset-path /home/ubuntu/tensorflow_workspace/2023Game/data/combined_88_test --calibration-file arucotag_roi_detector.calib
python3 ~/2023RobotCode/zebROS_ws/src/tf_object_detection/src/onnx_to_tensorrt.py arucotag_roi_detector.onnx --output arucotag_roi_detector_int8_batch10.engine --fp16 --input-width=1088 --batch-size=10 --int8 --max-workspace-size=1073741824 --dataset-path /home/ubuntu/tensorflow_workspace/2023Game/data/combined_88_test --calibration-file arucotag_roi_detector.calib
