controller_list:
  - name: minifrc_arm_joint_position_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - base_arm
      - second_stage_arm