chimera:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  

  # Position Controllers ---------------------------------------
  left_front_angle_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_front_angle_wheel
    pid: {p: 10.0, i: 0.0, d: 0.0}

  left_front_drive_velocity_controller:
      type: velocity_controllers/JointVelocityController
      joint: left_front_drive_wheel
      pid: {p: 10.0, i: 0.0, d: 0.0}