#!/bin/bash

set -e
set -o pipefail

docker run -it --privileged --net=host -v /tmp/.X11-unix:/tmp/.X11-unix \
 -v $HOME/2018Offseason:/home/ubuntu/2018Offseason \
 -e DISPLAY=$DISPLAY --user ubuntu frc900/zebros-dev:latest /bin/bash
