#!/bin/bash

dev_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
dev_dir="$( dirname "$dev_dir" )"

set -e
set -o pipefail

docker run -it --privileged --net=host -v /tmp/.X11-unix:/tmp/.X11-unix \
 -v $dev_dir/2018Offseason:/home/ubuntu/2018Offseason \
 -e DISPLAY=$DISPLAY --user ubuntu frc900/zebros-beta2019-dev:latest /bin/bash
