#!/bin/bash

dev_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
dev_dir="$( dirname "$dev_dir" )"

set -e
set -o pipefail

docker run "$@" -it --gpus all --net=host -v  /tmp/.X11-unix:/tmp/.X11-unix \
 -v $HOME/2022RobotCode:/home/ubuntu/.2022RobotCode.readonly \
 -v /dev:/dev --privileged \
 --shm-size=8G \
 -e DISPLAY=$DISPLAY -e NVIDIA_DRIVER_CAPABILITIES=all --user ubuntu frc900/zebros-noetic-dev:latest /bin/bash
