#!/bin/bash

dev_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
dev_dir="$( dirname "$dev_dir" )"

set -e
set -o pipefail

docker run "$@" -it --net=host -v  /tmp/.X11-unix:/tmp/.X11-unix \
 -v $HOME/2023RobotCode:/home/ubuntu/.2023RobotCode.readonly \
 --ipc=host \
 -v /mnt/hgfs/Zebracorns:/mnt/hgfs/Zebracorns \
  --shm-size=8G \
 -e DISPLAY=$DISPLAY --privileged --user ubuntu frc900/zebros-2023-dev:latest /bin/bash
