#!/bin/bash

dev_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
dev_dir="$( dirname "$dev_dir" )"

set -e
set -o pipefail

docker run -it --net=host -v /tmp/.X11-unix:/tmp/.X11-unix \
 -v $HOME/2019RobotCode:/home/ubuntu/2019RobotCode \
 -e DISPLAY=$DISPLAY --device=/dev/bus/usb/002/030 --user ubuntu frc900/zebros-2019-dev:latest /bin/bash
