elevator_controller_2023:
    type: elevator_controller_2023/ElevatorController_2023

    elevator_joint: [ 'elevator_leader', 'elevator_follower']
    fourbar_joint: 'four_bar'

    dynamic_reconfigure: true
    max_height_val: 1.4

    four_bar_max_extension: 0.65 # tbd, in meters
    four_bar_min_extension: 0.24 # tbd, in meters

    four_bar_parallel_bar_length: 0.127
    four_bar_diagonal_bar_length: 0.243
    four_bar_intake_length: 0.22

    arb_feed_forward_high: 0.04
    arb_feed_forward_low: 0.03

    arb_feed_forward_angle: 0.01
    straight_up_angle: 0.52
    
    motion_magic_velocity: 3.0 # could be 3.5 or 3 
    motion_magic_acceleration: 7.0 # could be 9.0 or 7
    motion_s_curve_strength: 8 # Maps to v6 motion magic jerk value

    # How quickly the elevator moves down when zeroing itself
    elevator_zeroing_percent_output: -0.2 # TODO : tune me

    # If there are no negative velocity readings while zeroing
    # for this amount of time, assume the elevator is stuck
    # or has hit bottom and the limit switch is broken.  Stop
    # trying to drive down to prevent killing the motor
    elevator_zeroing_timeout:  2.0
    stage_2_height: 0.7213
    elevator_leader:
        type: talon_controllers/TalonFXProControllerInterface 
        joint: elevator_leader
        close_loop_values:
            - {kP: 0.288, kI: 0.000, kD: 0.00, kV: 0.12, kS: 0}
        invert_output: clockwise_positive

        # linear position along 
        #conversion_factor: 0.00626535
        # Linear converion - radian per / m
        sensor_to_mechanism_ratio: 159.61
        # TODO : figure out what value this should be
        # Only need one direction, to
        # prevent the elevator from running off the top
        softlimit_forward_threshold: 1.412 
        softlimit_forward_enable: True

        # CHECK THIS
        feedback_type: IntegratedSensor

        # TODO : bottom limit switch config
        reverse_limit_switch_type: "NormallyOpen"
        reverse_limit_enable: True

        neutral_deadband: 0.001

        dynamic_reconfigure: True

    elevator_follower: 
        joint: elevator_follower

        #invert_output: counterclockwise_positive
        control_oppose_master_direction: True
        dynamic_reconfigure: false
