generic_hw_control_loop:
  loop_hz: 100
  cycle_time_error_threshold: 0.01
  canifier_read_hz: 100
  cancoder_read_hz: 100
  #some processes have lower frequencies than the main control loop
  ctre_mc_read_hz: 100
  pcm_read_hz: 20
  pdh_read_hz: 20
  pdp_read_hz: 20
  ph_read_hz: 20
  robot_iteration_hz: 20
  spark_max_read_hz: 100
  joystick_read_hz: 50
  match_data_read_hz: 2
  robot_controller_read_hz: 20
  as726x_read_hz: 7


# Settings for ros_control hardware interface
# Map a name for each valid joint to a CAN id
hardware_interface:

   joints:
       - {name: robot_code_ready_rio, local: true, type: ready}
       - {name: robot_code_ready_jetson, local: false, type: ready}

joint_state_controller_rio:
   type:         joint_state_controller/JointStateController
   publish_rate: 100

# Used to listen for remote joint states published from the given topic
# (in this case the Jetson) and copy them to internal copies of
# joint data
joint_state_listener_controller_rio:
    type:      state_listener_controller/JointStateListenerController
    topic:     /frcrobot_jetson/joint_states

match_state_controller:
   type:         match_state_controller/MatchStateController
   publish_rate: 20
