fr_angle_motionmagic_controller:
  type: talon_controllers/TalonMotionMagicCloseLoopController 
  joint: fr_angle
  feedback_type: RemoteSensor0
  remote_feedback_filter0: CANCoder
  remote_feedback_device_id0: 12
  sensor_initialization_strategy: BootToAbsolutePosition
  close_loop_values:
      - {p: 2.25, i: 0.000, d: 4.0, f: 0.28, i_zone: 0}
  invert_output: false
  sensor_phase: false
  neutral_deadband: 0.01
  peak_output_forward: 1.0
  peak_output_reverse: -1.0
  nominal_output_forward: 0.0
  nominal_output_reverse: 0.0
  motion_cruise_velocity: 45
  motion_acceleration: 153.3
  voltage_compensation_enable: true
  voltage_compensation_saturation: 12
  velocity_measurement_period: Period_10Ms
  velocity_measurement_window: 4
  dynamic_reconfigure: True
  #status_1_general_period: 100
  #status_2_feedback0_period: 100
  #status_1_general_period: 10
  #status_2_feedback0_period: 20
  status_3_quadrature_period: 250
  #status_4_aintempvbat_period: 160
  #status_6_misc_period: 0
  #status_7_commstatus_period: 0
  status_8_pulsewidth_period: 250
  status_9_motprofbuffer_period: 250
  #status_10_motionmagic_period: 160
  #status_11_uartgadgeteer_period: 250
  #status_12_feedback1_period: 250
  #status_13_base_pidf0_period: 160
  #status_14_turn_pidf1_period: 250
  status_15_firmwareapistatus_period: 250
  #status_17_targets1_period: 0
  #status_17_brushless_current_period: 0

br_angle_motionmagic_controller:
  type: talon_controllers/TalonMotionMagicCloseLoopController 
  joint: br_angle
  feedback_type: RemoteSensor0
  remote_feedback_filter0: CANCoder
  remote_feedback_device_id0: 14
  sensor_initialization_strategy: BootToAbsolutePosition
  close_loop_values:
      - {p: 2.25, i: 0.000, d: 4.0, f: 0.28, i_zone: 0}
  invert_output: false
  sensor_phase: false
  neutral_deadband: 0.01
  peak_output_forward: 1.0
  peak_output_reverse: -1.0
  nominal_output_forward: 0.0
  nominal_output_reverse: 0.0
  motion_cruise_velocity: 45
  motion_acceleration: 153.3
  voltage_compensation_enable: true
  voltage_compensation_saturation: 12
  velocity_measurement_period: Period_10Ms
  velocity_measurement_window: 4
  dynamic_reconfigure: True
  #status_1_general_period: 100
  #status_2_feedback0_period: 100
  #status_1_general_period: 10
  #status_2_feedback0_period: 20
  status_3_quadrature_period: 250
  #status_4_aintempvbat_period: 160
  #status_6_misc_period: 0
  #status_7_commstatus_period: 0
  status_8_pulsewidth_period: 250
  status_9_motprofbuffer_period: 250
  #status_10_motionmagic_period: 160
  #status_11_uartgadgeteer_period: 250
  #status_12_feedback1_period: 250
  #status_13_base_pidf0_period: 160
  #status_14_turn_pidf1_period: 250
  status_15_firmwareapistatus_period: 250
  #status_17_targets1_period: 0
  #status_17_brushless_current_period: 0
fl_angle_motionmagic_controller:
  type: talon_controllers/TalonMotionMagicCloseLoopController 
  joint: fl_angle
  feedback_type: RemoteSensor0
  remote_feedback_filter0: CANCoder
  remote_feedback_device_id0: 11
  sensor_initialization_strategy: BootToAbsolutePosition
  close_loop_values:
      - {p: 2.25, i: 0.000, d: 4.0, f: 0.28, i_zone: 0}
  invert_output: false
  sensor_phase: false
  neutral_deadband: 0.01
  peak_output_forward: 1.0
  peak_output_reverse: -1.0
  nominal_output_forward: 0.0
  nominal_output_reverse: 0.0
  motion_cruise_velocity: 45
  motion_acceleration: 153.3
  voltage_compensation_enable: true
  voltage_compensation_saturation: 12
  velocity_measurement_period: Period_10Ms
  velocity_measurement_window: 4
  dynamic_reconfigure: True
  #status_1_general_period: 100
  #status_2_feedback0_period: 100
  #status_1_general_period: 10
  #status_2_feedback0_period: 20
  status_3_quadrature_period: 250
  #status_4_aintempvbat_period: 160
  #status_6_misc_period: 0
  #status_7_commstatus_period: 0
  status_8_pulsewidth_period: 250
  status_9_motprofbuffer_period: 250
  #status_10_motionmagic_period: 160
  #status_11_uartgadgeteer_period: 250
  #status_12_feedback1_period: 250
  #status_13_base_pidf0_period: 160
  #status_14_turn_pidf1_period: 250
  status_15_firmwareapistatus_period: 250
  #status_17_targets1_period: 0
  #status_17_brushless_current_period: 0
bl_angle_motionmagic_controller:
  type: talon_controllers/TalonMotionMagicCloseLoopController 
  joint: bl_angle
  feedback_type: RemoteSensor0
  remote_feedback_filter0: CANCoder
  remote_feedback_device_id0: 13
  sensor_initialization_strategy: BootToAbsolutePosition
  close_loop_values:
      - {p: 2.25, i: 0.000, d: 4.0, f: 0.28, i_zone: 0}
  invert_output: false
  sensor_phase: false
  neutral_deadband: 0.01
  peak_output_forward: 1.0
  peak_output_reverse: -1.0
  nominal_output_forward: 0.0
  nominal_output_reverse: 0.0
  motion_cruise_velocity: 45
  motion_acceleration: 153.3
  voltage_compensation_enable: true
  voltage_compensation_saturation: 12
  velocity_measurement_period: Period_10Ms
  velocity_measurement_window: 4
  dynamic_reconfigure: True
  #status_1_general_period: 100
  #status_2_feedback0_period: 100
  #status_1_general_period: 10
  #status_2_feedback0_period: 20
  status_3_quadrature_period: 250
  #status_4_aintempvbat_period: 160
  #status_6_misc_period: 0
  #status_7_commstatus_period: 0
  status_8_pulsewidth_period: 250
  status_9_motprofbuffer_period: 250
  #status_10_motionmagic_period: 160
  #status_11_uartgadgeteer_period: 250
  #status_12_feedback1_period: 250
  #status_13_base_pidf0_period: 160
  #status_14_turn_pidf1_period: 250
  status_15_firmwareapistatus_period: 250
  #status_17_targets1_period: 0
  #status_17_brushless_current_period: 0
