bl_cancoder_controller:
    type:       cancoder_controller/CANCoderController
    joint_name: bl_cancoder
    magnet_offset: 1.24866
    # dynamic_reconfigure: True
    # sensor_direction: Clockwise_Positive
    # enable_read_thread: False

fl_cancoder_controller:
    type:       cancoder_controller/CANCoderController
    joint_name: fl_cancoder
    magnet_offset: 2.71515
    # dynamic_reconfigure: True
    # sensor_direction: Clockwise_Positive
    # enable_read_thread: False

br_cancoder_controller:
    type:       cancoder_controller/CANCoderController
    joint_name: br_cancoder
    magnet_offset: -0.273049
    # dynamic_reconfigure: True
    # sensor_direction: Clockwise_Positive
    # enable_read_thread: False

fr_cancoder_controller:
    type:       cancoder_controller/CANCoderController
    joint_name: fr_cancoder
    magnet_offset: 0.357418
    # dynamic_reconfigure: True
    # sensor_direction: Clockwise_Positive
    # enable_read_thread: False