pivot_cancoder_controller:
    type:      cancoder_controller/CANCoderController
    joint_name: shooter_pivot_cancoder
    sensor_direction: Clockwise_Positive
    dynamic_reconfigure: True
    magnet_offset: 1.5953400194010667
    enable_read_thread: True