arm_cancoder_controller:
    type:      cancoder_controller/CANCoderController
    joint_name: arm_cancoder
    dynamic_reconfigure: True
    magnet_offset: -2.886 # straight up
    enable_read_thread: True