
bl_cancoder_controller:
    type:      cancoder_controller/CANCoderController
    joint_name: bl_cancoder
    magnet_offset: 2.5770877236478773
    dynamic_reconfigure: False
    enable_read_thread: False

fl_cancoder_controller:
    type:      cancoder_controller/CANCoderController
    joint_name: fl_cancoder
    magnet_offset: 0.4172427743048944
    dynamic_reconfigure: False
    enable_read_thread: False

br_cancoder_controller:
    type:      cancoder_controller/CANCoderController
    joint_name: br_cancoder
    magnet_offset: 1.217980745581199
    dynamic_reconfigure: False
    enable_read_thread: False

fr_cancoder_controller:
    type:      cancoder_controller/CANCoderController
    joint_name: fr_cancoder
    magnet_offset: 2.715145994557585
    dynamic_reconfigure: False
    enable_read_thread: False