pivot_cancoder_controller:
    type:      cancoder_controller/CANCoderController
    joint_name: shooter_pivot_cancoder
    sensor_direction: Clockwise_Positive
    dynamic_reconfigure: True
    magnet_offset: 0.5246214294568894
    enable_read_thread: True