# fl -> bl, fr -> fl, bl -> br, br -> fr
swerve_drive_controller:
    bl_angle:
        offset: 2.00031
    br_angle:
        offset: -3.10171
    fl_angle:
        offset: 1.40666
    fr_angle:
        offset: 0.590583