swerve_drive_controller:
    type: talon_swerve_drive_controller/TalonFXProSwerveDriveController

    latency_compensation_group: latency_compensation # joint name

    speed: ['fl_drive', 'fr_drive', 'bl_drive', 'br_drive']
    steering: ['fl_angle', 'fr_angle', 'bl_angle', 'br_angle']
    publish_cmd: True
    odometry_publishing_frequency: 250.0
    publish_odometry_to_base_transform: True
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

    wheel_radius: 0.048 # m
    cmd_vel_timout: 0.5
    max_speed: 7 # Potentially raise, otherwise swerve math will limit max motor speed

    # TODO : multiplied ctre5 values by 12v/ 100% output as a guess, need to verify
    # This would be a good guess, except we're using % duty cycle, not voltage out
    # f_s is static feedfoward - the is the min motor output used by
    # the speed motors to overcome static friction
    
    f_s: 0.019
    # Small amount of power given to motors to get the swerve to coast to a 
    # stop rather than snapping on brake mode immediately
    stopping_ff: 0.019

    # TODO - currently not used, but perhaps map to kV / kA values 
    # passed to the motor controller
    f_a: 0.005
    f_v: 0.0379

    # TODO : move this into sensor_to_mechanism_ratio for Falcons
    ratio_encoder_to_rotations: 0.148148148 # Test me, will show up in odom results

    encoder_drive_get_V_units: 1
    encoder_drive_set_V_units: 1
    encoder_drive_get_P_units: 1
    encoder_drive_set_P_units: 1
    encoder_steering_get_units: 1
    encoder_steering_set_units: 1

    # 17.5 in (0.4445 m) long, 15.5 in (0.3937) wide
    # fl : +x, +y
    # fr : +x, -y
    # bl : -x, +y
    # br : -x, -y
    wheel_coords: [[0.19685, 0.22225], [0.19685, -0.22225], [-0.19685, 0.22225], [-0.19685, -0.22225]]
    parking_config_time_delay: 0.75
    drive_speed_time_delay: 0.125
    use_cos_scaling: True # scale motor speed by how close angle motors are to setpoints
    fl_drive:
        joint: fl_drive
        close_loop_values:
            - {kP: 0.50, kI: 0.0, kD: 0.0, kV: 0.118, kS: 0.0}
        #current_limit_continuous_amps: 15
        #current_limit_peak_amps: 25
        #current_limit_peak_msec: 50
        #current_limit_enable: True
        voltage_closed_loop_ramp_period: 0.10
        dynamic_reconfigure: True
        neutral_mode: Brake
        forward_limit_enable: False
        reverse_limit_enable: False
    fr_drive:
        joint: fr_drive
        close_loop_values:
            - {kP: 0.50, kI: 0.0, kD: 0.0, kV: 0.118, kS: 0.0}
        #current_limit_continuous_amps: 15
        #current_limit_peak_amps: 25
        #current_limit_peak_msec: 50
        #current_limit_enable: True
        voltage_closed_loop_ramp_period: 0.10
        dynamic_reconfigure: True
        neutral_mode: "Brake"
        forward_limit_enable: False
        reverse_limit_enable: False
    bl_drive:
        joint: bl_drive
        close_loop_values:
            - {kP: 0.50, kI: 0.0, kD: 0.0, kV: 0.118, kS: 0.0}
        #feedback_type: IntegratedSensor
        #current_limit_continuous_amps: 15
        #current_limit_peak_amps: 25
        #current_limit_peak_msec: 50
        #current_limit_enable: True
        voltage_closed_loop_ramp_period: 0.10
        dynamic_reconfigure: True
        neutral_mode: "Brake"
        forward_limit_enable: False
        reverse_limit_enable: False
    br_drive:
        joint: br_drive
        close_loop_values:
            - {kP: 0.50, kI: 0.0, kD: 0.0, kV: 0.118, kS: 0.0}
        #feedback_type: IntegratedSensor
        #current_limit_continuous_amps: 15
        #current_limit_peak_amps: 25
        #current_limit_peak_msec: 50
        #current_limit_enable: True
        voltage_closed_loop_ramp_period: 0.10
        dynamic_reconfigure: True
        neutral_mode: "Brake"
        forward_limit_enable: False
        reverse_limit_enable: False

    fl_angle:
        joint: fl_angle
        # invert: clockwise_positive
        feedback_sensor_source: FusedCANcoder
        feedback_remote_sensor_id: 12
        close_loop_values:
            - {kP: 100.0, kI: 0.0, kD: 0.75, kV: 1.5, kS: 0.0}
        motion_magic_cruise_velocity: 0.0
        motion_magic_expo_kV: 0.5
        motion_magic_expo_kA: 0.5
        forward_limit_enable: False
        reverse_limit_enable: False
        rotor_to_sensor_ratio: 12.8
        sensor_to_mechanism_ratio: 1.0
        dynamic_reconfigure: True
    fr_angle:
        joint: fr_angle
        # invert: clockwise_positive
        feedback_sensor_source: FusedCANcoder
        remote_feedback_device_id0: 14
        close_loop_values:
            - {kP: 100.0, kI: 0.0, kD: 0.75, kV: 1.5, kS: 0.0}
        motion_magic_cruise_velocity: 0.0
        motion_magic_expo_kV: 0.5
        motion_magic_expo_kA: 0.5
        forward_limit_enable: False
        reverse_limit_enable: False
        rotor_to_sensor_ratio: 12.8
        sensor_to_mechanism_ratio: 1.0
        dynamic_reconfigure: True
    br_angle:
        joint: br_angle
        # invert: clockwise_positive
        feedback_sensor_source: FusedCANcoder
        remote_feedback_device_id0: 13
        close_loop_values:
            - {kP: 100.0, kI: 0.0, kD: 0.75, kV: 1.5, kS: 0.0}
        motion_magic_cruise_velocity: 0.0
        motion_magic_expo_kV: 0.5
        motion_magic_expo_kA: 0.5
        forward_limit_enable: False
        reverse_limit_enable: False
        rotor_to_sensor_ratio: 12.8
        sensor_to_mechanism_ratio: 1.0
        dynamic_reconfigure: True
    bl_angle:
        joint: bl_angle
        # invert: clockwise_positive
        feedback_sensor_source: FusedCANcoder
        remote_feedback_device_id0: 11
        close_loop_values:
            - {kP: 100.0, kI: 0.0, kD: 0.75, kV: 1.5, kS: 0.0}
        motion_magic_cruise_velocity: 0.0
        motion_magic_expo_kV: 0.5
        motion_magic_expo_kA: 0.5
        forward_limit_enable: False
        reverse_limit_enable: False
        rotor_to_sensor_ratio: 12.8
        sensor_to_mechanism_ratio: 1.0
        dynamic_reconfigure: True

# Stand-alone controller used to tune PID constants
swerve_angle_phoenix6_controller:
    type: talonfxpro_controllers/TalonFXProMotionMagicExpoVoltageController
    joint: bl_angle
    feedback_sensor_source: RemoteCANcoder
    remote_feedback_device_id0: 13
    close_loop_values:
        - {kP: 100.0, kI: 0.0, kD: 0.75, kV: 1.5, kS: 0}
    motion_magic_cruise_velocity: 0.0
    motion_magic_expo_kV: 0.5
    motion_magic_expo_kA: 0.5
    forward_limit_enable: False
    reverse_limit_enable: False
    dynamic_reconfigure: True
