bl_cancoder_controller:
    type:      cancoder_controller/CANCoderController
    joint_name: bl_cancoder
    magnet_offset: 2.5832236467994196
    dynamic_reconfigure: True
    # sensor_direction: Clockwise_Positive
    # enable_read_thread: False

fl_cancoder_controller:
    type:      cancoder_controller/CANCoderController
    joint_name: fl_cancoder
    magnet_offset: -3.0081363250437425
    dynamic_reconfigure: True
    # sensor_direction: Clockwise_Positive
    # enable_read_thread: False

br_cancoder_controller:
    type:      cancoder_controller/CANCoderController
    joint_name: br_cancoder
    magnet_offset: 1.538582730249298
    dynamic_reconfigure: True
    # sensor_direction: Clockwise_Positive
    # enable_read_thread: False

fr_cancoder_controller:
    type:      cancoder_controller/CANCoderController
    joint_name: fr_cancoder
    magnet_offset: -2.1751847572218392
    dynamic_reconfigure: True
    # sensor_direction: Clockwise_Positive
    # enable_read_thread: False