cube_time: 0.0
cone_time: 0.0
server_timeout: 20.0
path_zero_timeout: 5.0
current_threshold: 150.0 # some arbitrary unit
joint: intake_leader # for current sensing
time_before_reverse: 0.0

intake_speed: 0.5
cone_outtake_speed: 0.8
cube_outtake_speed: 0.2
intake_small_speed: 0.09

dynamic_reconfigure: true