# [elevator, fourbar]
# these are absolute positions
# first point is ignored

fourbar_tolerance: 0.05
elevator_tolerance: 0.03

paths:
  # mid_cone: [[0.0, 0.0], [0.0, 0.7], [0.55, 0.7], [0.7, 0.64]]
  # high_cone: [[0.0, 0.0], [0.0, 0.7], [0.55, 0.7], [0.7, 0.64], [1.2, 1.0]]

  # TODO assert that the starting point is where we are within epsilon.

  intake_cone_cube: [[0.05, 0.35], [0.0, 1.75]]
  intake_vertical_cone: [[0.05, 0.35], [0.18, 1.7]] # was [0.0, 1.1] for second
  intake_double_substation: [[0.0, 0.35], [0.0, 0.75], [1.3, 1.7]] # change this (it's currently high cone)
  intake_double_substation_reverse: [[1.3, 1.7], [1.3, 0.75], [0.0, 0.75], [0.0, 0.35]] # change this (it's currently high cone)

  # flip_fourbar_after_intaking: [[0.0, 1.3], [0.54, 1.3], [0.6, 4.75], [0.45, 4.75]]
  # flip_fourbar_after_intaking: [[0.0, 1.3], [0.0, 0.35]] # intake from above
  # unflip_fourbar: [[0.45, 4.75], [0.6, 4.75], [0.54, 0.7], [0.0, 0.7], [0.0, 0.0]]

  # The transition from [0.6, 4.75] to [0.55, 0.7] is almost a full rotation of the four bar.
  # This means that it will likely hit into the mid node cone pole (it is extended past 0.7)
  # I don't know how to resolve this. It is at 4.75, but we need to get it to 0.7, without going above 0.7.
  # We could unfold the four bar earlier as we're preparing to place?
  # old paths:
  # mid_cone: [[0.0, 0.35], [0.0, 0.7], [0.55, 0.7], [0.7, 0.64]]
  # high_cone: [[0.0, 0.35], [0.0, 0.7], [1.0, 0.7], [1.2, 1.0]]

  # DO NOT REVERSE THESE WHATEVER YOU DO
  # not sure why we go up then down to unfold...



  # mid_cone: [[0.45, 4.75], [0.6, 4.75], [0.55, 0.7], [0.7, 0.64]] # will actually start at [0.45, 4.75]
  # high_cone: [[0.45, 4.75], [0.6, 4.75], [1.0, 0.7], [1.2, 1.3]] # maybe fourbar 1.3

  # mid_cone_reverse: [[0.7, 0.64], [0.55, 0.7], [0.0, 0.7], [0.0, 0.0]]
  # high_cone_reverse: [[1.2, 1.3], [1.0, 0.7], [0.0, 0.7], [0.0, 0.0]]

  # mid_cone_auto: [[0.0, 0.0], [0.0, 0.7], [0.55, 0.7], [0.7, 0.64]]
  # high_cone_auto: [[0.0, 0.0], [0.0, 0.7], [1.0, 0.7], [1.2, 1.3]]


  # mid_cube: [[0.45, 4.75], [0.6, 4.75], [0.55, 0.7], [0.7, 0.5]] # this is a guess
  # high_cube: [[0.45, 4.75], [0.6, 4.75], [1.0, 0.7], [1.2, 0.8]] # also a guess

  # mid_cube_reverse: [[0.7, 0.5], [0.55, 0.7], [0.0, 0.7], [0.0, 0.0]]
  # high_cube_reverse: [[1.2, 0.8], [1.0, 0.7], [0.0, 0.7], [0.0, 0.0]]

  mid_cone: [[0.0, 0.35], [0.0, 0.75], [0.55, 0.75], [0.7, 0.64]] # will actually start at [0.45, 4.75]
  # elevator now can move higher
  high_cone: [[0.0, 0.35], [0.0, 0.75], [1.0, 0.75], [1.28, 1.25]] # maybe fourbar 1.3

  mid_cone_reverse: [[0.7, 0.64], [0.55, 0.75], [0.0, 0.75], [0.0, 0.35]]
  high_cone_reverse: [[1.28, 1.25], [1.0, 0.75], [0.0, 0.75], [0.0, 0.35]]

  mid_cone_auto: [[0.0, 0.35], [0.0, 0.75], [0.55, 0.75], [0.7, 0.64]]
  high_cone_auto: [[0.0, 0.35], [0.0, 0.75], [1.0, 0.75], [1.28, 1.25]]


  mid_cube: [[0.0, 0.35], [0.0, 0.75], [0.55, 0.75], [0.7, 0.5]] # this is a guess
  high_cube: [[0.0, 0.35], [0.0, 0.75], [1.0, 0.75], [1.25, 0.8]] # also a guess

  mid_cube_reverse: [[0.7, 0.5], [0.55, 0.75], [0.0, 0.75], [0.0, 0.35]]
  high_cube_reverse: [[1.25, 0.8], [1.0, 0.75], [0.0, 0.75], [0.0, 0.35]]

  
  # could be 1.3 but probably better not to slam fully extended four bar fast down
  # commented out, old starting place
  # hybrid_cone: [[0.45, 4.75], [0.6, 4.75], [0.54, 0.7], [0.0, 1.3]]
  # hybrid_cube: [[0.45, 4.75], [0.6, 4.75], [0.54, 0.7], [0.0, 1.3]]

  # hybrid_cone_reverse: [[0.0, 1.3], [0.0, 0.0]]
  # hybrid_cube_reverse: [[0.0, 1.3], [0.0, 0.0]]
  

  zero: [[0.0, 0.0], [0.0, 0.0]]

  elevator_test: [[0.0, 0.0], [0.0, 0.7], [0.5, 0.7]]
  elevator_test_2: [[0.0, 0.0], [0.0, 0.7], [0.5, 0.7], [0.6, 1.0]]

  test1: [[0.0, 0.0], [0.0, 0.7]]
  test2: [[0.0, 0.7], [0.5, 0.7]]
