# [elevator, fourbar]
# they move in that order going forward, opposite going back
# these are absolute positions
# home = [0, 0], must come first in a path

paths:
  mid_cone: [[0.0, 0.0], [0.55, 0.82], [0.7, 0.64]]
  high_cone: [[0.0, 0.0], [0.55, 0.82], [0.7, 0.64], [1.2, 1.0]]

  intake_cone_cube: [[0.0, 0.0], [0.0, 1.9]]
  intake_vertical_cone: [[0.0, 0.0], [0.0, 1.7]]