# [elevator, fourbar]
# these are absolute positions
# home = [0, 0], must come first in a path

fourbar_tolerance: 0.03
elevator_tolerance: 0.03

paths:
  mid_cone: [[0.0, 0.0], [0.0, 0.82], [0.55, 0.82], [0.7, 0.64]]
  high_cone: [[0.0, 0.0], [0.0, 0.82], [0.55, 0.82], [0.7, 0.64], [1.2, 1.0]]

  intake_cone_cube: [[0.0, 0.0], [0.0, 1.9]]
  intake_vertical_cone: [[0.0, 0.0], [0.0, 1.7]]

  elevator_test: [[0.0, 0.0], [0.0, 0.82], [0.5, 0.82]]
  elevator_test_2: [[0.0, 0.0], [0.0, 0.82], [0.5, 0.82], [0.6, 1.0]]