# not respected
note_distance_away: 5.0 # meters if note if farther away then we don't rumble
preshooter_limit_switch_name: preshooter_limit_switch
intake_limit_switch_name: diverter_limit_switch
claw_limit_switch_name: claw_limit_switch

rumble_on_note: 30000 # out of 65535