extend_speed: 20.0
extend_acceleration: 40.0
fast_retract_speed: 20.0
trap_retract_speed: 20.0
fast_retract_acceleration: 40.0
trap_retract_acceleration: 40.0
extend_height: 55.0
trap_height: 15.0
fast_height: 15.0
joint_name: climb_leader
loop_rate: 50.0
tolerance: 10.0
pivot_angle: 1.7
min_pivot_angle: 1.65