converter_subscribers:
  yolo_detect:
    topic: "/tf_object_detection_zedx_front/obj_detection_msg"
  screen_to_world:  
    topic: "/tf_object_detection_zedx_front/object_detection_world"
  tag_to_world_back:
    topic: "/apriltag_zedx_back/tag_detection_world"
  tag_to_world_front:
    topic: "/apriltag_zedx_front/tag_detection_world"
  sim_screen_to_world:  
    topic: "/tf_object_detection/object_detection_world"

converter_publishers:
  output:
    topic: "norfair/input"
    queue_size: 1
