nav_msgs/Path position_path
nav_msgs/Path position_waypoints
nav_msgs/Path velocity_path
nav_msgs/Path velocity_waypoints
int32[] waypointsIdx

# Linear and angular tolerances for finishing path
# Set to non-zero to override config defaults
float64 final_pos_tol
float64 final_rot_tol

bool dont_go_to_start
---
bool timed_out
bool success
---
float32 percent_complete
float32 percent_next_waypoint
int32 current_waypoint