# Aliases are short commands to replace long ones.

alias crossbuild='~/2023RobotCode/zebROS_ws/cross_build.sh'
alias deploy='~/2023RobotCode/scripts/deploy.sh'
alias diaglaunch='roslaunch controller_node 2022_test_indexer_intake_combined.launch'
alias hwlaunch='roslaunch controller_node 2022_compbot_combined.launch'
alias killros='~/2023RobotCode/zebROS_ws/kill_ros_.sh'
alias natbuild='~/2023RobotCode/zebROS_ws/native_build.sh'
alias rosjet='source ~/2023RobotCode/zebROS_ws/ROSJetsonMaster.sh'
alias rosstd='source ~/2023RobotCode/zebROS_ws/ROSStandard.sh'
alias simlaunch='roslaunch controller_node 2023_compbot_combined.launch hw_or_sim:=sim joy_or_key:=key button_box:=false'
alias ls='ls --color'
alias driversim='rqt --standalone rqt_driver_station_sim'
alias driverdash='rqt --standalone rqt_dashboard --qt-binding pyqt'
alias axclient='rosrun actionlib_tools axclient.py'
