# Aliases are short commands to replace long ones.

alias crossbuild='~/2023RobotCode/zebROS_ws/cross_build.sh'
alias deploy='~/2023RobotCode/scripts/deploy.sh'
alias diaglaunch='echo "Not implmented yet! Check command_aliases.sh"'
alias hwlaunch='roslaunch controller_node 2024_compbot_combined.launch'
alias practice='roslaunch controller_node 2024_practice_combined.launch'
alias killros='~/2023RobotCode/zebROS_ws/kill_ros_.sh'
alias natbuild='~/2023RobotCode/zebROS_ws/native_build.sh'
alias rosjet='source ~/2023RobotCode/zebROS_ws/ROSJetsonMaster.sh'
alias rosstd='source ~/2023RobotCode/zebROS_ws/ROSStandard.sh'
alias simlaunch='roslaunch controller_node 2024_compbot_combined.launch hw_or_sim:=sim'
alias fieldsim='roslaunch controller_node 2024_compbot_combined.launch hw_or_sim:=sim stage_sim:=true'
alias ls='ls --color'
alias driversim='rqt --standalone rqt_driver_station_sim'
alias axclient='rosrun actionlib_tools axclient.py'
alias ddr='rosrun rqt_reconfigure rqt_reconfigure'
