# params/zedm.yaml
# Parameters for Stereolabs ZED mini camera
---

general:
    camera_model:               'zedm'
    resolution:                 3           # '0': HD2K, '1': HD1080, '3': HD720, '5': VGA, '6': AUTO
    grab_frame_rate:            30          # Frequency of frame grabbing for internal SDK operations

depth:
    min_depth:                  0.1             # Min: 0.1, Max: 3.0 - Default 0.3 - Note: reducing this value wil require more computational power and GPU memory
    max_depth:                  10.0            # Max: 20.0  
