float64 data # either percent output (0-1) or position (radians I think?)
bool use_percent_output # %_out or motion_magic
uint8 RETRACT=0
uint8 EXTEND=1
uint8 TRANSITION=2
uint8 profile # see constants above
---
