noise_delta_t: 1.0
map_frame_id: 'map'
odom_frame_id: 'zed_objdet_odom'

field_dims:
  x_min: -2.0
  x_max: 9.144
  y_min: -2.0
  y_max: 4.572

init_dims:
  x_min: 0.0
  x_max: 1.524
  y_min: 0.0
  y_max: 3.048

num_particles: 200

noise_stdev:
  position: 0.025
  rotation: 0.001
  # Modifiers for noise stddev when robot is moving or stopped
  # Allows for more accurate localization when stopped by using
  # a lower stddev for noise when the robot is at rest.
  stopped_pos_noise_multiplier: 1.0
  stopped_rot_noise_multiplier: 1.0
  moving_pos_noise_multiplier: 1.0
  moving_rot_noise_multiplier: 1.0

rotation_threshold: 0.25

camera_sigmas: [ 0.500, 0.500 ]

bearing_only: false

beacons:
  - [-1.72, -0.2, "100"]
  - [-1.72, 0.48, "600"]
  - [-1.72, 1.145, "200"]
  - [-1.72, 1.638, "400"]
  - [-1.72, 2.263, "500"]
  - [-1.72, 3.103, "300"]
