#!/usr/bin/env python

import sys

from rqt_dashboard.dashboard import Dashboard
from rqt_gui.main import Main

plugin = 'rqt_dashboard'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
